<?xml version="1.0" encoding="utf-8"?><Database Name="EscolaDB" Class="EscolaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=THUANNY\SQLEXPRESS;Initial Catalog=EscolaDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="EscolaDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Escola" Member="Escolas">
    <Type Name="Escola">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UF" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CH" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LC" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Matematica" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Redacao" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
</Database>