#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscolaRest.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EscolaDB")]
	public partial class EscolaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEscola(Escola instance);
    partial void UpdateEscola(Escola instance);
    partial void DeleteEscola(Escola instance);
    #endregion
		
		public EscolaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["EscolaDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EscolaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EscolaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EscolaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EscolaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Escola> Escolas
		{
			get
			{
				return this.GetTable<Escola>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Escola")]
	public partial class Escola : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nome;
		
		private string _UF;
		
		private System.Nullable<double> _CN;
		
		private System.Nullable<double> _CH;
		
		private System.Nullable<double> _LC;
		
		private System.Nullable<double> _Matematica;
		
		private System.Nullable<double> _Redacao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnUFChanging(string value);
    partial void OnUFChanged();
    partial void OnCNChanging(System.Nullable<double> value);
    partial void OnCNChanged();
    partial void OnCHChanging(System.Nullable<double> value);
    partial void OnCHChanged();
    partial void OnLCChanging(System.Nullable<double> value);
    partial void OnLCChanged();
    partial void OnMatematicaChanging(System.Nullable<double> value);
    partial void OnMatematicaChanged();
    partial void OnRedacaoChanging(System.Nullable<double> value);
    partial void OnRedacaoChanged();
    #endregion
		
		public Escola()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UF", DbType="VarChar(50)")]
		public string UF
		{
			get
			{
				return this._UF;
			}
			set
			{
				if ((this._UF != value))
				{
					this.OnUFChanging(value);
					this.SendPropertyChanging();
					this._UF = value;
					this.SendPropertyChanged("UF");
					this.OnUFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CN", DbType="Float")]
		public System.Nullable<double> CN
		{
			get
			{
				return this._CN;
			}
			set
			{
				if ((this._CN != value))
				{
					this.OnCNChanging(value);
					this.SendPropertyChanging();
					this._CN = value;
					this.SendPropertyChanged("CN");
					this.OnCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CH", DbType="Float")]
		public System.Nullable<double> CH
		{
			get
			{
				return this._CH;
			}
			set
			{
				if ((this._CH != value))
				{
					this.OnCHChanging(value);
					this.SendPropertyChanging();
					this._CH = value;
					this.SendPropertyChanged("CH");
					this.OnCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LC", DbType="Float")]
		public System.Nullable<double> LC
		{
			get
			{
				return this._LC;
			}
			set
			{
				if ((this._LC != value))
				{
					this.OnLCChanging(value);
					this.SendPropertyChanging();
					this._LC = value;
					this.SendPropertyChanged("LC");
					this.OnLCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matematica", DbType="Float")]
		public System.Nullable<double> Matematica
		{
			get
			{
				return this._Matematica;
			}
			set
			{
				if ((this._Matematica != value))
				{
					this.OnMatematicaChanging(value);
					this.SendPropertyChanging();
					this._Matematica = value;
					this.SendPropertyChanged("Matematica");
					this.OnMatematicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Redacao", DbType="Float")]
		public System.Nullable<double> Redacao
		{
			get
			{
				return this._Redacao;
			}
			set
			{
				if ((this._Redacao != value))
				{
					this.OnRedacaoChanging(value);
					this.SendPropertyChanging();
					this._Redacao = value;
					this.SendPropertyChanged("Redacao");
					this.OnRedacaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
